### ISSUE TITLE
Gtk-WARNING **: cannot open display

### ISSUE THREAD

**Issue by buklrr** [cinemast/OpenMosaic#1]
Hi,

Doing the following command generates the error **Gtk-WARNING **: cannot open display**
`sudo python Stitcher.py baseimage.jpg 20 rgb targetimage.jpg`

My system is a Raspberry Pi 2, running on Rasbian.

Do you have any idea?

Thx
Julien

**Comment by cinemast** [comment]
Do you have a graphical environment installed and running?

**Comment by cinemast** [comment]
If not, comment all lines starting with cv2.imshow, those are visualisation functions.
